// Первая форма с выбором предмета, имени

package my.QuizView;

/**
 *
 * @author rushano4ka1987
 */
public class QuizViewUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizViewUI
     */
    public QuizViewUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelName = new javax.swing.JPanel();
        LabelName = new javax.swing.JLabel();
        TextFieldSurname = new javax.swing.JTextField();
        LabelSurname = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        LabelNameTest = new javax.swing.JLabel();
        ComboBoxChooseOfSubject = new javax.swing.JComboBox();
        LabelChooseOfSubject = new javax.swing.JLabel();
        PanelofStartTesting = new javax.swing.JPanel();
        ButtonStartTesting = new javax.swing.JButton();
        ButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelName.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));

        LabelName.setText("Имя");
        LabelName.setToolTipText("");

        TextFieldSurname.setCaretColor(new java.awt.Color(204, 204, 255));
        TextFieldSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSurnameActionPerformed(evt);
            }
        });

        LabelSurname.setText("Фамилия");
        LabelSurname.setToolTipText("");

        TextFieldName.setCaretColor(new java.awt.Color(204, 204, 255));
        TextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNameActionPerformed(evt);
            }
        });

        LabelNameTest.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LabelNameTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelNameTest.setText("Тест. Введите имя.");

        ComboBoxChooseOfSubject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1С", "GIMP", "Базы данных", "English" }));
        ComboBoxChooseOfSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxChooseOfSubjectActionPerformed(evt);
            }
        });

        LabelChooseOfSubject.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelChooseOfSubject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelChooseOfSubject.setText("Выберите предмет.");

        javax.swing.GroupLayout PanelNameLayout = new javax.swing.GroupLayout(PanelName);
        PanelName.setLayout(PanelNameLayout);
        PanelNameLayout.setHorizontalGroup(
            PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNameLayout.createSequentialGroup()
                .addGroup(PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelNameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ComboBoxChooseOfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNameLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(LabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNameTest, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
            .addGroup(PanelNameLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(LabelChooseOfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelNameLayout.setVerticalGroup(
            PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelNameTest, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(PanelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelChooseOfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxChooseOfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        PanelofStartTesting.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));

        ButtonStartTesting.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        ButtonStartTesting.setText("Начать тестирование");
        ButtonStartTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartTestingActionPerformed(evt);
            }
        });

        ButtonClose.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        ButtonClose.setText("Выход");
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelofStartTestingLayout = new javax.swing.GroupLayout(PanelofStartTesting);
        PanelofStartTesting.setLayout(PanelofStartTestingLayout);
        PanelofStartTestingLayout.setHorizontalGroup(
            PanelofStartTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelofStartTestingLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(ButtonStartTesting, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelofStartTestingLayout.setVerticalGroup(
            PanelofStartTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelofStartTestingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelofStartTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(ButtonStartTesting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelofStartTesting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(PanelName, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelofStartTesting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    private void TextFieldSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSurnameActionPerformed

    private void TextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNameActionPerformed

    private void ComboBoxChooseOfSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxChooseOfSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxChooseOfSubjectActionPerformed

    private void ButtonStartTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartTestingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonStartTestingActionPerformed

    private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizViewUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizViewUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClose;
    private javax.swing.JButton ButtonStartTesting;
    private javax.swing.JComboBox ComboBoxChooseOfSubject;
    private javax.swing.JLabel LabelChooseOfSubject;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelNameTest;
    private javax.swing.JLabel LabelSurname;
    private javax.swing.JPanel PanelName;
    private javax.swing.JPanel PanelofStartTesting;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldSurname;
    // End of variables declaration//GEN-END:variables
}
